global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "fastapi"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ["nginx:80"]

  - job_name: "nestjs"
    metrics_path: /api/v2/metrics
    static_configs:
      - targets: ["nginx:80"]

  # Direct scrape targets to bypass Nginx DNS issues
  - job_name: "fastapi-direct"
    metrics_path: /metrics
    static_configs:
      - targets: ["fastapi:8000"]

  - job_name: "nestjs-direct"
    metrics_path: /metrics
    static_configs:
      - targets: ["nestjs:3000"]